### ISSUE TITLE
Gradle 5.6 configuration

### ISSUE THREAD

**Issue by realdadfish** [tbroyer/gradle-errorprone-plugin#35] opened 2019-08-27 17:38 UTC
Apparently with Gradle 5.6 the Java task configuration got lazy, so this does no longer work:

```groovy
 tasks.withType(JavaCompile) {
            options.errorprone.errorproneArgs += [
                        '-Xep:ImmutableEnumChecker:ERROR',
                        '-Xep:MissingOverride:ERROR',
                        ...
           ]
}
```

but spits out an error:

```
No signature of method: org.gradle.api.internal.provider.DefaultListProperty.plus() is applicable for argument types: (ArrayList) values: [[-Xep:ImmutableEnumChecker:ERROR, -Xep:MissingOverride:ERROR, ...]]
  Possible solutions: value(java.lang.Iterable), value(org.gradle.api.provider.Provider), value(java.lang.Iterable), value(org.gradle.api.provider.Provider), is(java.lang.Object), split(groovy.lang.Closure)
```

The configuration via the left-shift operator also does no longer work:

```
No signature of method: org.gradle.api.internal.provider.DefaultListProperty.leftShift() is applicable for argument types: (String) values: [-Xep:ImmutableEnumChecker:ERROR]
```

Changing ` errorproneArgs += []` to `errorproneArgs = []` fixed it for me.

**Comment by tbroyer** [comment] 2019-08-27 18:10
Duplicate of #29, and unrelated to Gradle 5.6; you probably also upgraded from an earlier version of the plugin to 0.8

**Closed as completed by tbroyer** 2019-08-27 18:10 UTC

**Comment by gregallen** [comment] 2020-02-25 09:34
also seeing this - very hard to track down this fix in a closed issue - perhaps doc could be updated?

**Comment by tbroyer** [comment] 2020-02-25 10:21
As explained in #29, this was documented in the [release notes](https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v0.8).
I've updated the _Migrating from versions 0.0.x_ section where the diffs were still using `<<`, and added a note about all the properties being lazy, but I can't do much more:
* the README covers the latest version
* release notes document changes between versions
* versions 0.x, as per semantic versionning, made no commitment to API stability
