### ISSUE TITLE
Add support for refaster

### ISSUE THREAD

**Issue by koppor** [tbroyer/gradle-errorprone-plugin#41] opened 2020-04-23 21:43 UTC
This is a follow-up of https://github.com/tbroyer/gradle-errorprone-plugin-v0.0.x/issues/65.

[Refaster](https://errorprone.info/docs/refaster) is now a plugin of error prone. Thus, I thought that the gradle plugin would support it, too.

For a first version I would expect that

- `src/refaster/` contains `*.refaster`
- A gradle task `refaster` applies each refaster file to each java file in the compile source set. Also for the test source set.

In later versions, one can configure the source set and the files to apply. (IMHO not needed).

**Comment by tbroyer** [comment] 2020-04-25 12:59
> [Refaster](https://errorprone.info/docs/refaster) is now a plugin of error prone.

What makes you say that:interrobang: Refaster hasn't changed since 2017 (which even predates the original issue you're linking to):
* https://github.com/google/error-prone/blame/master/refaster/pom.xml (recent changes are only the version of Refaster, and the version of the auto-service dependency)
* https://github.com/google/error-prone/commits/master/refaster/src

What you're suggesting here is adding [patching](https://errorprone.info/docs/patching) support to the plugin with possibly a special support for autodiscovering refaster files.
Patching is already tracked by #38, and I don't quite like your autodiscovery approach: aren't those one-off tasks? then wouldn't it be better to invoke the task passing the paths to the refaster files on the command line? Actually, those paths aren't much different from the names of the checks to patch, which brings us back to #38.

Closing as a duplicate of #38 for now; can reopen if you make the case for specific support for refaster files.

**Closed as completed by tbroyer** 2020-04-25 12:59 UTC

**Comment by koppor** [comment] 2020-04-28 05:08
Thank you for the long reply. I thought that refaster would automatically change my files according **custom** refastr rules, whereas #38 seems to point to error-prone hard-coded rules (if I understand http://errorprone.info/docs/patching correctly).

Not sure whether autopatch will read `.refaster` files (hand-crafted by the project) in `/src/refaster/` automatically and call the refaster module of error prone.

My personal use case is to rewrite `assertEquals(true, ...)` to `assertTrue(...)`. This is IMHO not available in checkstyle and errorprone.

It should be rewritten each time when a contributor submits a PR. I'd like to have a way to say to newcomers: Hey, your code is not good. Therefore, I came to checkstyle. Checkstyle does not support it, but some issue pointed to refaster (which does more than just reporting). By searching for "refaster" and "gradle", I came to https://github.com/tbroyer/gradle-errorprone-plugin-v0.0.x/issues/65, which lead me to here.

Thus, this is NOT a one-time task. In other words: I am faced with new contributors and new Java programmers nearly each week. I want to reduce load to the human code-reviewers by adding tool support for easy-to-catch code issues.

**Comment by tbroyer** [comment] 2020-04-28 07:30
Whether you use ErrorProne checks' suggested fixes or Refaster files, patching is done the same way (it's just that instead of the name of a check, you use `refaster:` followed by the path to a Refaster file). If you can do one, you can do the other.

If I understand your usecase correctly, you may actually want to write a custom ErrorProne check to flag misuse of `assertEquals(true, …)` instead of `assertTrue(…)` (to fail the build), and then use patching to make it easy to fix those errors (I'd then rather use a suggested fix than Refaster).
A custom Checkstyle rule would work as well, but without the automatic fixing AFAICT.

In any case, even using Refaster only like you envisioned, you can use the same snippet as in https://github.com/tbroyer/gradle-errorprone-plugin/issues/38#issuecomment-565162822, but building the `-XepPatchChecks` value by reading files in `src/refaster/`; something like (using Kotlin DSL):
```kotlin
   errorproneArgs.add("-XepPatchChecks:${fileTree("src/refaster/") { include("**/*.refaster") }.joinToString(",") { "refaster:$it" } }")
```
(fwiw, I would actually rather use `errorproneArgumentProviders` to compute the value as late as possible, declaring `src/refaster/**/*.refaster` as task inputs)
